name: Sync to Hugging Face spaces
on:
  push:
    branches: [ main ] # Agar aapki branch ka naam master hai to yahan master likhein

  # To run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://LofarBoy:$HF_TOKEN@huggingface.co/spaces/Rizvi082/Render_bot main
